### ISSUE TITLE
A genjava dependency

### ISSUE THREAD

**Issue by stonier** [ros/message_generation#1]
Feasability of an official genjava generator - the main worry would be introducing a large dependency on openjdk or some such since the generator needs to compile java class files into a jar.

This could be a build_depend only though.

Are there any issues/worries with this?

**Comment by tfoote** [comment]
The size of the dependencies is the only major issue.  If it becomes part of the recommended core anyone building from source will get it and it's dependencies.  For the binaries the build farm won't really notice.

**Comment by stonier** [comment]
Certainly wouldn't be an issue for me - ros requires and uses so many dependencies anyway. So long as the runtime is not affected. We have a couple of other issues though, so I'll engage in some more discussion and come back to this here.

**Comment by damonkohler** [comment]
If the plan is to integrate Java messages into the deb distribution of ROS, then I think we should talk adding a system-wide Maven cache to /opt/ros/turtle. Dropping artifacts there in the right locations does not require adding a Java dependency to ROS debs.

**Comment by dirk-thomas** [comment]
Since we are not that knowledgeable for Java please consider providing a pull request which provides all the necessary infrastructure.

**Comment by stonier** [comment]
I'll need to sync with Damon on what he might actually be talking about there. I won't have time to hit this for a while though, so no rush.

**Comment by stonier** [comment]
I have an initial [genjava](https://github.com/stonier/genjava) working implementation that can be tested via these [instructions](http://wiki.ros.org/rosjava/Tutorials/indigo/Source%20Installation). It is not a final version (needs to move to file-by-file generators instead of package genarators as rosjava currently does) but it is a good moment to stop here and question whether it is worth pursuing this direction.

Key points to discuss:
- Genjava or not to Genjava
- Has a compile step
- If made official via `message_generation`:
  - Becomes the default for everyone's source workspace.
  - Indirectly brings in a java `build_depends` for everybody.

**Genjava or not to Genjava**

This would seem to be the correct place to do message generation. Right now rosjava just parses package paths looking for msg/srv files which are expected to be in the appropriate msg or srv subfolder. This does not generate a true list though - there is nothing stopping a user from having experimental copies (perhaps broken) of .msg/.srv files in a package. The true list is generated from those added with the `add_message_files` and `add_service_files` cmake macros. As a result, the current method is fragile and imposes a constraint on users that is not otherwise there.

Hooking into the genmsg infrastructure will generate this true list and trying to implement something similar outside it would be effort and reinventing the wheel. For this reason, I'd like to move ahead with genjava.

**The Compile Step**

I can't find a reasonable way around this compile step. Sure we could just create the .java files, but as far as I know, you can't package and depend on java sources in gradle/maven like you can with c++ headers.

_@damonkholer any ideas?_

 This obviously increases build time for users and the build farm. How much of a concern is this?

**Java as a build_depends, Default generator**

I don't know that it's necessary to have it in `message_generation` as an officially supported language. This would be bring in the java dependency and force 99% of users to disable it via the environment variable (I already have this nuisance with lisp). 

_Is inclusion in `message_generation` deps necessary to getting the build farm to genjava for us though?_

There is not much point having genjava unless we can get the build farm generating for us otherwise you'd be forced to include every single message generating package in your source workspace.

**Comment by dirk-thomas** [comment]
I think this was discussed a long time ago but close the ticket and provide a summary of the rational:

With the proposed generator requiring Java it can't be considered as a default generator. Otherwise Java would be a strict dependency on every platform where ROS is being built which is not realistic.
