### ISSUE TITLE
CMake var to override set of generators?

### ISSUE THREAD

**Issue by mikepurvis** [ros/message_generation#6]
Currently if I'm building a full system and want to exclude some generators, it's not enough to blacklist the repos from my workspace—I have to also fork this package to remove them from the CATKIN_DEPENDS list.

Not a huge inconvenience, but it also wouldn't be too difficult to support overriding the list with a var like `ROS_MESSAGE_GENERATORS` or similar.

Note that doing a non-required `find_package` on each one in _this_ package to test whether they're present also doesn't work unless they are switched to be build_depends, which would also be fine with me as an approach, but makes this package heavier at build time.

**Comment by dirk-thomas** [comment]
Have you tried the env var `ROS_LANG_DISABLE`: see http://wiki.ros.org/ROS/EnvironmentVariables#ROS_LANG_DISABLE.

**Comment by mikepurvis** [comment]
Oh interesting, that is new to me. It looks like it does do the right thing, however with some caveats:

- The disabled generators still need to be present in the workspace or you get find_package errors— the disable list is not causing them to be filtered from the CATKIN_DEPENDS list in this package.
- The disabled list needs to be set any time a message package is built, so it seems like it's more of an end-user thing ("in my develspace, don't waste time building messages for languages I don't use").

Based on this, I feel there would still be room for a CMake var to turn them off at the source.
